// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4-xkSWAcD8CSEChcEHfxq9pIQiB6NW0',
    appId: '1:924317884101:web:9e48a6a26664faabc39aac',
    messagingSenderId: '924317884101',
    projectId: 'kart-oyunu-78f24',
    authDomain: 'kart-oyunu-78f24.firebaseapp.com',
    databaseURL: 'https://kart-oyunu-78f24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kart-oyunu-78f24.firebasestorage.app',
    measurementId: 'G-CH0LEV2SV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjLyVs-zuNxxwLm9-PbmIEP9YuLYEUbNA',
    appId: '1:924317884101:android:75117382b3d6d89cc39aac',
    messagingSenderId: '924317884101',
    projectId: 'kart-oyunu-78f24',
    databaseURL: 'https://kart-oyunu-78f24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kart-oyunu-78f24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ00wZUtZ9Vng_i6hYD-Wj0BATHdNs7I8',
    appId: '1:924317884101:ios:96afef93f9c1aa51c39aac',
    messagingSenderId: '924317884101',
    projectId: 'kart-oyunu-78f24',
    databaseURL: 'https://kart-oyunu-78f24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kart-oyunu-78f24.firebasestorage.app',
    iosClientId: '924317884101-l5tdvbja2uvf6mvs0aevrknerii2a6nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartOyunu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ00wZUtZ9Vng_i6hYD-Wj0BATHdNs7I8',
    appId: '1:924317884101:ios:96afef93f9c1aa51c39aac',
    messagingSenderId: '924317884101',
    projectId: 'kart-oyunu-78f24',
    databaseURL: 'https://kart-oyunu-78f24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kart-oyunu-78f24.firebasestorage.app',
    iosClientId: '924317884101-l5tdvbja2uvf6mvs0aevrknerii2a6nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.kartOyunu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR4-xkSWAcD8CSEChcEHfxq9pIQiB6NW0',
    appId: '1:924317884101:web:99d8d24854c0a07dc39aac',
    messagingSenderId: '924317884101',
    projectId: 'kart-oyunu-78f24',
    authDomain: 'kart-oyunu-78f24.firebaseapp.com',
    databaseURL: 'https://kart-oyunu-78f24-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'kart-oyunu-78f24.firebasestorage.app',
    measurementId: 'G-PW6LHPNKM0',
  );
}
